language: java
before_install:
  - "export DISPLAY=:99.0"
  - "export TERM=dumb"
  - "sh -e /etc/init.d/xvfb start"

install: 
  - sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ trusty universe multiverse"
  - sudo apt-get update -qq
  - sudo apt-get install -y --force-yes libopencv2.4-jni  libopencv2.4-java  libdc1394-22-dev libdc1394-22 libdc1394-utils
  - TERM=dumb ./gradlew --refresh-dependencies --stacktrace
script:
    - TERM=dumb ./gradlew  compileJava  javadoc test --stacktrace
cache:
  directories:
  - $HOME/.m2

jdk:
  - oraclejdk8

# for running tests on Travis CI container infrastructure for faster builds
sudo: true
dist: trusty


after_failure:
  - "cat ./build/test-results/*.xml"
