language: java
install: 
  - sudo wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo add-apt-repository ppa:cwchien/gradle -y
  - sudo apt-get update -qq
  - sudo apt-get install -y --force-yes gradle
script: 
  - gradle compileJava jar javadoc test 
cache:
  directories:
  - $HOME/.m2

jdk:
  - oraclejdk8

# for running tests on Travis CI container infrastructure for faster builds
sudo: true
dist: trusty
