package com.neuronrobotics.replicator.driver;

import java.io.File;
import java.util.Arrays;

public class Slic3r extends ExternalSlicer {
	
	private static String executableLocation=null;
	

	public Slic3r(	double nozzle_diameter,
					double [] printCenter,
					double filimentDiameter,
					double extrusionMultiplier,
					int tempreture,
					int bedTempreture,
					double layerHeight,
					int wallThickness,
					boolean useSupportMaterial,
					double retractLength,
					int travilSpeed,
					int perimeterSpeed,
					int bridgeSpeed,
					int gapFillSpeed,
					int infillSpeed,
					int supportMaterialSpeed,
					
					int smallPerimeterSpeedPercent,
					int externalPerimeterSpeedPercent,
					int solidInfillSpeedPercent,
					int topSolidInfillSpeedPercent,
					int supportMaterialInterfaceSpeedPercent,
					int firstLayerSpeedPercent
					) {
		
		if(!new File(getExecutableLocation()).canExecute())
			throw new RuntimeException("Slicer binary must be executable. ");
		this.cmdline=Arrays.asList(getExecutableLocation(),
				"--nozzle-diameter="+nozzle_diameter,
				"--print-center=("+printCenter[0]+","+printCenter[1]+")",
				"--filament-diameter="+filimentDiameter,
				"--extrusion-multiplier="+extrusionMultiplier,
				"--temperature="+tempreture,
				"--bed-temperature="+bedTempreture,
				"--layer-height="+layerHeight,
				"--perimeters="+wallThickness,
				"--avoid-crossing-perimeters",
				useSupportMaterial?"--support-material":" ",
				"--retract-length="+retractLength,
				//"--skirts=2",
				//"--repair",
				"--travel-speed="+travilSpeed,
				"--perimeter-speed="+perimeterSpeed,
				"--bridge-speed="+bridgeSpeed,
				"--gap-fill-speed="+gapFillSpeed,
				"--infill-speed="+infillSpeed,
				"--support-material-speed="+supportMaterialSpeed,
				
				"--small-perimeter-speed="+smallPerimeterSpeedPercent+"%",
				"--external-perimeter-speed="+externalPerimeterSpeedPercent+"%",
				"--solid-infill-speed="+solidInfillSpeedPercent+"%",
				"--top-solid-infill-speed="+topSolidInfillSpeedPercent+"%",
				"--support-material-interface-speed="+supportMaterialInterfaceSpeedPercent+"%",
				"--first-layer-speed="+firstLayerSpeedPercent+"%",
				"--notes=\"Generated by com.neuronrobotics.replicator.driver.Slic3r.java\""
			);
	}


	public static String getExecutableLocation() {
		return executableLocation;
	}


	public static void setExecutableLocation(String executableLocation) {
		Slic3r.executableLocation = executableLocation;
	}
	
//	public static void main(String args[]) throws Exception {
//		ExternalSlicer slicer=new Slic3r(new MiracleGrueMaterialData());
//		FileInputStream stlFile=new FileInputStream(args[0]);
//		FileOutputStream dumpFile=new FileOutputStream(args[0]+"-dump.gcode");
//		slicer.slice(stlFile, dumpFile);
//	}

}
