package com.neuronrobotics.replicator.driver;

import java.util.Arrays;

public class Slic3r extends ExternalSlicer {
	
	

	public Slic3r(	double nozzle_diameter,
					double [] printCenter,
					double filimentDiameter,
					double extrusionMultiplier,
					double tempreture,
					double bedTempreture,
					double layerHeight,
					int wallThickness,
					boolean useSupportMaterial,
					double retractLength
					) {
		this.cmdline=Arrays.asList("slic3r",
				"--nozzle-diameter "+nozzle_diameter,
				"--print-center ("+printCenter[0]+","+printCenter[0]+")",
				"--filament-diameter "+filimentDiameter,
				"--extrusion-multiplier "+extrusionMultiplier,
				"--temperature "+tempreture,
				"--bed-temperature "+bedTempreture,
				"--layer-height "+layerHeight,
				"--perimeters "+wallThickness,
				" --avoid-crossing-perimeters",
				useSupportMaterial?"--support-material":" ",
				"--retract-length "+retractLength,
				"--skirts",
				"--notes Generated by com.neuronrobotics.replicator.driver.Slic3r.java"
			);
	}
	
//	public static void main(String args[]) throws Exception {
//		ExternalSlicer slicer=new Slic3r(new MiracleGrueMaterialData());
//		FileInputStream stlFile=new FileInputStream(args[0]);
//		FileOutputStream dumpFile=new FileOutputStream(args[0]+"-dump.gcode");
//		slicer.slice(stlFile, dumpFile);
//	}

}
